promote_package.yml - removed manaul trigger, added webhook trigger, tagging and promotion changes

diff --git a/.github/workflows/promote_package.yml b/.github/workflows/promote_package.yml
--- a/.github/workflows/promote_package.yml
+++ b/.github/workflows/promote_package.yml
@@ -1,12 +1,9 @@
 name: Promote Python Package
 
 on:
-  workflow_dispatch:
-    inputs:
-      package_version:
-        description: 'Package version to promote (e.g., 0.0.1)'
-        required: true
-        type: string
+  repository_dispatch:
+    types:
+      - package_synchronized
 
 env:
   CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
@@ -23,6 +20,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
       - name: Get OIDC token
         run: |
           # Generate the OIDC Token in GitHub Actions
@@ -38,26 +36,45 @@ jobs:
           oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
           oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}
 
-      - name: Get package identifier and promote
+      - name: Get Information from Webhook
         run: |
-          # Query for the package and get its identifier
-          PACKAGE_QUERY="filename:${PACKAGE_NAME}-${{ github.event.inputs.package_version }}.tar.gz"
-          echo "Searching for package with query: $PACKAGE_QUERY"
+          # Extract package identifier from the webhook payload
+          PACKAGE_IDENTIFIER=$(echo "${{ github.event.client_payload.package_identifier }}" | jq -r '.identifier_perm')
+          if [ -z "$PACKAGE_IDENTIFIER" ] || [ "$PACKAGE_IDENTIFIER" = "null" ]; then
+            echo "Failed to extract package identifier from webhook payload"
+            exit 1
+          fi
+          echo "Extracted Package Identifier: $PACKAGE_IDENTIFIER"
+          echo "PACKAGE_IDENTIFIER=$PACKAGE_IDENTIFIER" >> $GITHUB_ENV
+
+      - name: Tag Package with ready-for-production
+        run: |
+          cloudsmith tag add \
+            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$PACKAGE_IDENTIFIER \
+            ready-for-production
+          echo "Tagged package $PACKAGE_IDENTIFIER with 'ready-for-production'"
+
+      - name: Get Packages with ready-for-production tag and Promote
+        run: |
+          PACKAGE_QUERY="tag:ready-for-production"
+          echo "Searching for all packages with query: $PACKAGE_QUERY"
           
           PACKAGE_DATA=$(cloudsmith list package ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} -q "$PACKAGE_QUERY" -F json)
           
           # Extract the identifier_perm using jq
-          IDENTIFIER=$(echo "$PACKAGE_DATA" | jq -r '.data[0].identifier_perm')
+          IDENTIFIERS=$(echo "$PACKAGE_DATA" | jq -r '.data[].identifier_perm')
           
-          if [ -z "$IDENTIFIER" ] || [ "$IDENTIFIER" = "null" ]; then
-            echo "Failed to find package identifier"
+          if [ -z "$IDENTIFIERS" ] ; then
+            echo "Failed to find package with 'ready-for-production' tag"
             exit 1
           fi
           
-          echo "Found package identifier: $IDENTIFIER"
+          echo "Found package identifier: $IDENTIFIERS"
           
-          # Promote package using the identifier
-          cloudsmith mv --yes \
-            ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
-            ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
+          # Promote package from staging to production
+          for IDENTIFIER in $IDENTIFIERS; do
+            echo "Promoting package: $IDENTIFIER"
+            cloudsmith mv --yes \
+              ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }}/$IDENTIFIER \
+              ${{ env.CLOUDSMITH_PRODUCTION_REPO }}
         shell: bash
